//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo lo genero una herramienta.
//
//     Los cambios en este archivo podrian causar un comportamiento incorrecto y se perderan si
//     se regenera el codigo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tareas_con_Prioridades
{


    public partial class Default
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automaticamente.
        /// Para modificarlo, mueva la declaracion del campo del archivo del disenador al archivo de codigo subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// control lblTotal - Contador total de tareas.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotal;

        /// <summary>
        /// control lblPendientes - Contador de tareas pendientes.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendientes;

        /// <summary>
        /// control lblEnProgreso - Contador de tareas en progreso.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEnProgreso;

        /// <summary>
        /// control lblCompletadas - Contador de tareas completadas.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCompletadas;

        /// <summary>
        /// control txtDescripcion - TextBox para la descripcion de la tarea.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;

        /// <summary>
        /// control txtResponsable - TextBox para el responsable de la tarea.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtResponsable;

        /// <summary>
        /// control ddlPrioridad - DropDownList para seleccionar prioridad (Alta, Media, Baja).
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlPrioridad;

        /// <summary>
        /// control btnAgregar - Boton para agregar nueva tarea.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAgregar;

        /// <summary>
        /// control lblMensaje - Label para mensajes de validacion.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMensaje;

        /// <summary>
        /// control rblFiltros - RadioButtonList para filtrar tareas por estado.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButtonList rblFiltros;

        /// <summary>
        /// control rptTareas - Repeater para la visualizacion dinamica de la lista de tareas.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptTareas;

        /// <summary>
        /// control pnlVacio - Panel que muestra mensaje cuando no hay tareas.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlVacio;

        /// <summary>
        /// control btnMarcarTodas - Boton para marcar todas las tareas como completadas.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnMarcarTodas;

        /// <summary>
        /// control btnEliminarCompletadas - Boton para eliminar tareas completadas.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnEliminarCompletadas;
    }
}
